# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings, global variables
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adam M. Jacobs
email: ajacobs@pa.msu.edu
description: >- # this means to ignore newlines until "baseurl:"
    The professional website of computational nuclear astrophysicist
    Adam M. Jacobs.
address:
    Adam M. Jacobs <br>
    Dept of Physics and Astronomy <br>
    Michigan State University <br>
    567 Wilson Road, Room 3255 <br>
    Biomedical and Physical Sciences Bldg <br>
    East Lansing, Michigan 48824 <br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amjacobs.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "adam_m_jcbs"
github_username:  "adam-m-jcbs"
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
#logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
#repo: "https://github.com/daviddarnes/alembic"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
#avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - TODO
    - README.md
    - .git
    - util

# Build settings
#markdown: kramdown
markdown: rdiscount
theme: alembic-jekyll-theme
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-mentions
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-redirect-from
    - jemoji

# Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
    username: adam_m_jcbs # jekyll-seo-tag > Owners twitter username
author: AdamJacobs # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
    name: Adam M. Jacobs # jekyll-seo-tag > real name
    links:  # jekyll-seo-tag > social aliases (sameAs)
        - https://twitter.com/adam_m_jcbs
        - https://www.linkedin.com/in/adamjcbs
        - https://github.com/adam-m-jcbs

# Jekyll settings
sass:
    style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/New_York # Timezone for blog posts and alike

# Site navigation
navigation_header:
    Home: /
    CV: /cv/
    Research: /research/
    Notes: /notes/

navigation_footer:
    Site powered by Jekyll: https://jekyllrb.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
    Twitter: https://twitter.com/adam_m_jcbs
    LinkedIn: https://www.linkedin.com/in/adamjcbs
    GitHub: https://github.com/adam-m-jcbs

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
    Twitter: "#0d94e7"
    facebook: "#3B5998"
    #Google+: "#DC4E41"
    # Pinterest: "#BD081C"
    LinkedIn: "#0077B5"
    # tumblr: "#36465D"
    # Reddit: "#FF4500"
    # Hacker News: "#ff6600"
    # Designer News: "#2D72D9"
    # Email: ""

# Collections
collections:
    posts:
        title: Posts # Needed for Siteleaf
        output: true
        description: "My thoughts and ideas" # The post list page content
        feature_text: |
          Welcome to the blog
        feature_image: "https://picsum.photos/2560/600?image=866"

# Jekyll collections settings
defaults:
  -
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
